### ISSUE TITLE
Aeroengine data

### ISSUE THREAD

**Issue by ZhiyuanLi-c** [Amoiensis/AeroEngine_FaultDiagnosis#1]
First, Thank you for exposing the code publicly

But where can I download the dataset corresponding to the code?Is it public?

Best regards,
Zhiyuan

**Comment by Amoiensis** [comment]
非常感谢您对本项目的关注和支持，但是非常抱歉所涉及的发动机数据无法公开，希望项目中的相关思路和想法能够帮助到您。
如果您有相关的研究或者内容，非常希望您能和我一起完善这个项目，期待您的提交和加入。
